# Prueba de Modulos para Análisis No Supervisado

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Aura De La Garza G\Projects\GenAI-Music\unsupervised\raw_data\measure_features_raw.csv")

# <font color='Cyan'>Data en Estado Crudo</font>

In [3]:
df.head(10)

,suite,movement,file,measure_index,key_local,mode_local,measure_length_quarter,num_distinct_chords,most_common_chord_root,most_common_chord_type,...,pc_2,pc_3,pc_4,pc_5,pc_6,pc_7,pc_8,pc_9,pc_10,pc_11
0,data,1 Allemande Accomp.mid,C:\Users\Aura De La Garza G\Projects\GenAI-Mus...,1,C,major,4.0,1,9.0,min,...,0,0,0,0,0,0,0,0,0,0
1,data,1 Allemande Accomp.mid,C:\Users\Aura De La Garza G\Projects\GenAI-Mus...,2,C,major,4.0,1,2.0,min,...,0,0,0,0,0,0,0,0,0,0
2,data,1 Allemande Accomp.mid,C:\Users\Aura De La Garza G\Projects\GenAI-Mus...,3,C,major,4.0,1,2.0,min,...,0,0,0,0,0,0,0,0,0,0
3,data,1 Allemande Accomp.mid,C:\Users\Aura De La Garza G\Projects\GenAI-Mus...,4,C,major,4.0,1,2.0,min,...,0,0,0,0,0,0,0,0,0,0
4,data,1 Allemande Accomp.mid,C:\Users\Aura De La Garza G\Projects\GenAI-Mus...,5,C,major,4.0,1,11.0,triad,...,0,0,0,0,0,0,0,0,0,0
5,data,1 Allemande Accomp.mid,C:\Users\Aura De La Garza G\Projects\GenAI-Mus...,6,C,major,4.0,1,0.0,maj,...,0,0,0,0,0,0,0,0,0,0
6,data,1 Allemande Accomp.mid,C:\Users\Aura De La Garza G\Projects\GenAI-Mus...,7,C,major,4.0,1,0.0,maj,...,0,0,0,0,0,0,0,0,0,0
7,data,1 Allemande Accomp.mid,C:\Users\Aura De La Garza G\Projects\GenAI-Mus...,8,C,major,4.0,1,0.0,maj,...,0,0,0,0,0,0,0,0,0,0
8,data,1 Allemande Accomp.mid,C:\Users\Aura De La Garza G\Projects\GenAI-Mus...,9,C,major,4.0,1,0.0,maj,...,0,0,0,0,0,0,0,0,0,0
9,data,1 Allemande Accomp.mid,C:\Users\Aura De La Garza G\Projects\GenAI-Mus...,10,C,major,4.0,1,0.0,maj,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df['rhythmic_entropy'].value_counts()

rhythmic_entropy
-0.000000    13379
 0.918296      670
 0.591673      528
 0.970951      440
 1.000000      239
             ...
 1.867634        1
 1.488525        1
 1.960964        1
 1.356780        1
 1.459148        1
Name: count, Length: 88, dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18021 entries, 0 to 18020
Data columns (total 32 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   suite                   18021 non-null  object
 1   movement                18021 non-null  object
 2   file                    18021 non-null  object
 3   measure_index           18021 non-null  int64
 4   key_local               18021 non-null  object
 5   mode_local              18021 non-null  object
 6   measure_length_quarter  18021 non-null  float64
 7   num_distinct_chords     18021 non-null  int64
 8   most_common_chord_root  9880 non-null   float64
 9   most_common_chord_type  9880 non-null   object
 10  degree_relative_to_key  7038 non-null   float64
 11  function                18021 non-null  object
 12  melodic_range           18021 non-null  int64
 13  mean_interval           18021 non-null  float64
 14  large_jump_pct          18021 non-null  float64
 15  num_notes_melody        18021 non-null  int64
 16  avg_duration            18021 non-null  float64
 17  rhythmic_entropy        18021 non-null  float64
 18  most_common_duration    18021 non-null  object
 19  note_density            18021 non-null  int64
 20  pc_0                    18021 non-null  int64
 21  pc_1                    18021 non-null  int64
 22  pc_2                    18021 non-null  int64
 23  pc_3                    18021 non-null  int64
 24  pc_4                    18021 non-null  int64
 25  pc_5                    18021 non-null  int64
 26  pc_6                    18021 non-null  int64
 27  pc_7                    18021 non-null  int64
 28  pc_8                    18021 non-null  int64
 29  pc_9                    18021 non-null  int64
 30  pc_10                   18021 non-null  int64
 31  pc_11                   18021 non-null  int64
dtypes: float64(7), int64(17), object(8)
memory usage: 4.4+ MB

In [8]:
df.shape

(18021, 32)

In [9]:
def check_missing_values(dataframe):
    missing_values = dataframe.isnull().sum()
    missing_percentage = (missing_values / len(dataframe)) * 100
    missing_df = pd.DataFrame({'Missing Values': missing_values, 'Percentage': missing_percentage})
    return missing_df

In [10]:
check_missing_values(df)

                        Missing Values  Percentage
suite                                0    0.000000
movement                             0    0.000000
file                                 0    0.000000
measure_index                        0    0.000000
key_local                            0    0.000000
mode_local                           0    0.000000
measure_length_quarter               0    0.000000
num_distinct_chords                  0    0.000000
most_common_chord_root            8141   45.175074
most_common_chord_type            8141   45.175074
degree_relative_to_key           10983   60.945564
function                             0    0.000000
melodic_range                        0    0.000000
mean_interval                        0    0.000000
large_jump_pct                       0    0.000000
num_notes_melody                     0    0.000000
avg_duration                         0    0.000000
rhythmic_entropy                     0    0.000000
most_common_duration                 0    0.000000
note_density                         0    0.000000
pc_0                                 0    0.000000
pc_1                                 0    0.000000
pc_2                                 0    0.000000
pc_3                                 0    0.000000
pc_4                                 0    0.000000
pc_5                                 0    0.000000
pc_6                                 0    0.000000
pc_7                                 0    0.000000
pc_8                                 0    0.000000
pc_9                                 0    0.000000
pc_10                                0    0.000000
pc_11                                0    0.000000

# <font color='cyan'>Normalización de Variables Identificadoras</font>

In [11]:
df_id = pd.read_csv(r"C:\Users\Aura De La Garza G\Projects\GenAI-Music\unsupervised\curated_data\measure_features_identifiers.csv")

In [12]:
df_id.head()

,bwv,movement,measure_index,key_local,mode_local,measure_length_quarter,num_distinct_chords,most_common_chord_root,most_common_chord_type,degree_relative_to_key,...,pc_2,pc_3,pc_4,pc_5,pc_6,pc_7,pc_8,pc_9,pc_10,pc_11
0,BWV1013,Allemande,1,C,major,4.0,1,9.0,min,6.0,...,0,0,0,0,0,0,0,0,0,0
1,BWV1013,Allemande,2,C,major,4.0,1,2.0,min,2.0,...,0,0,0,0,0,0,0,0,0,0
2,BWV1013,Allemande,3,C,major,4.0,1,2.0,min,2.0,...,0,0,0,0,0,0,0,0,0,0
3,BWV1013,Allemande,4,C,major,4.0,1,2.0,min,2.0,...,0,0,0,0,0,0,0,0,0,0
4,BWV1013,Allemande,5,C,major,4.0,1,11.0,triad,7.0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
df['num_distinct_chords'].value_counts()

num_distinct_chords
0     8141
1     5781
2     3361
3      434
4      156
6       57
5       55
7       24
8        8
11       4
Name: count, dtype: int64

In [14]:
df_id[df_id['bwv']=='BWV1008']['movement'].value_counts()

movement
Menuet I_Ii    270
Gigue          170
Courante       147
Allemande      147
Prelude        139
Sarabande      126
Name: count, dtype: int64

In [15]:
df_id['movement'].value_counts()

movement
Courante              1994
Gigue                 1935
Prelude               1800
Fugue                 1758
Allemande             1537
Sarabande             1177
Bourree I_Ii           904
Gavotte I_Ii           880
Double                 773
Chaconne               578
Menuet I_Ii            540
Allegro Assai          459
Tempo Di Borea         405
Double Presto          363
Corrente               362
Allegro                348
Gavotte En Rondeau     326
Presto                 306
Minuet I_Ii            293
Boure                  219
Loure                  216
Adagio                 204
Allemanda              167
Boure Anglaise         135
Andante                119
Siciliano               89
Grave                   78
Largo                   56
Name: count, dtype: int64

# <font color='cyan'>Normalización de Variables Armónicas</font>

In [16]:
df_harmony = pd.read_csv(r"C:\Users\Aura De La Garza G\Projects\GenAI-Music\unsupervised\curated_data\measure_features_harmonic_normalized.csv")

In [17]:
df_harmony['most_common_chord_type'].value_counts()

most_common_chord_type
major      5578
minor      3322
unknown     980
Name: count, dtype: int64

# <font color='cyan'>Normalización de Variables Melódicas</font>

In [18]:
import pandas as pd

# ------------------------------------------------------------------
# Load melodic-normalized dataset
# ------------------------------------------------------------------

DATA_PATH = r"C:\Users\Aura De La Garza G\Projects\GenAI-Music\unsupervised\curated_data\measure_features_melodic_normalized.csv"

df = pd.read_csv(DATA_PATH)

print("Dataset shape:", df.shape)


# ------------------------------------------------------------------
# 1. Helper indicators overview
# ------------------------------------------------------------------

print("\n=== Melodic activity indicators ===\n")

display(
    df[["has_melodic_activity", "has_melodic_motion"]]
    .value_counts()
    .rename("count")
    .reset_index()
)


# ------------------------------------------------------------------
# 2. Zeros explained by melodic activity
# ------------------------------------------------------------------

print("\n=== melodic_range == 0 by melodic activity ===\n")

display(
    pd.crosstab(
        df["melodic_range"] == 0,
        df["has_melodic_motion"],
        rownames=["melodic_range == 0"],
        colnames=["has_melodic_motion"],
        margins=True
    )
)


print("\n=== mean_interval == 0 by melodic activity ===\n")

display(
    pd.crosstab(
        df["mean_interval"] == 0,
        df["has_melodic_motion"],
        rownames=["mean_interval == 0"],
        colnames=["has_melodic_motion"],
        margins=True
    )
)


# ------------------------------------------------------------------
# 3. Duration variables conditioned on activity
# ------------------------------------------------------------------

print("\n=== avg_duration distribution (active measures only) ===\n")

display(
    df.loc[df["has_melodic_activity"], "avg_duration"]
    .describe()
    .to_frame()
)


print("\n=== most_common_duration (active measures only) ===\n")

display(
    df.loc[df["has_melodic_activity"], "most_common_duration"]
    .value_counts()
    .head(10)
    .rename("count")
    .reset_index()
)


# ------------------------------------------------------------------
# 4. Large leap percentage sanity check
# ------------------------------------------------------------------

print("\n=== large_jump_pct == 0 interpretation ===\n")

display(
    pd.crosstab(
        df["large_jump_pct"] == 0,
        df["has_melodic_motion"],
        rownames=["large_jump_pct == 0"],
        colnames=["has_melodic_motion"],
        margins=True
    )
)


# ------------------------------------------------------------------
# 5. Single-note vs multi-note measures
# ------------------------------------------------------------------

print("\n=== num_notes_melody distribution ===\n")

display(
    df["num_notes_melody"]
    .value_counts()
    .sort_index()
    .rename("count")
    .reset_index()
)

Dataset shape: (18021, 36)

=== Melodic activity indicators ===

   has_melodic_activity  has_melodic_motion  count
0                  True                True  10370
1                 False               False   7182
2                  True               False    469

=== melodic_range == 0 by melodic activity ===

has_melodic_motion  False   True    All
melodic_range == 0
False                   0  10190  10190
True                 7651    180   7831
All                  7651  10370  18021

=== mean_interval == 0 by melodic activity ===

has_melodic_motion  False   True    All
mean_interval == 0
False                   0  10190  10190
True                 7651    180   7831
All                  7651  10370  18021

=== avg_duration distribution (active measures only) ===

       avg_duration
count  10839.000000
mean       0.528016
std        0.371782
min        0.166667
25%        0.266667
50%        0.500000
75%        0.571429
max        4.000000

=== most_common_duration (active measures only) ===

  most_common_duration  count
0                 0.25   4656
1                  0.5   4281
2                  1.0   1152
3                  1/3    288
4                  2.0    233
5                 0.75    157
6                  1/6     21
7                  1.5     19
8                  3.0     16
9                  4.0     11

=== large_jump_pct == 0 interpretation ===

has_melodic_motion   False   True    All
large_jump_pct == 0
False                    0   7588   7588
True                  7651   2782  10433
All                   7651  10370  18021

=== num_notes_melody distribution ===

    num_notes_melody  count
0                  0   7182
1                  1    469
2                  2    460
3                  3    398
4                  4    633
5                  5    580
6                  6    506
7                  7    638
8                  8   2538
9                  9    517
10                10    421
11                11    291
12                12    453
13                13    297
14                14    400
15                15    158
16                16   2080

# <font color='cyan'>Normalización de Variables Rítmicas</font>

In [19]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Aura De La Garza G\Projects\GenAI-Music\unsupervised\curated_data\measure_features_rhythmic_normalized.csv"
)

print("Minimum rhythmic entropy:", df["rhythmic_entropy"].min())

df["rhythmic_entropy"].value_counts().head(10)

Minimum rhythmic entropy: 0.0

rhythmic_entropy
-0.000000    13379
 0.918296      670
 0.591673      528
 0.970951      440
 1.000000      239
 1.500000      195
 0.764205      188
 0.721928      184
 0.779350      166
 0.371232      146
Name: count, dtype: int64

In [20]:
df.shape

(18021, 36)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18021 entries, 0 to 18020
Data columns (total 36 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   bwv                     18021 non-null  object
 1   movement                18021 non-null  object
 2   measure_index           18021 non-null  int64
 3   key_local               18021 non-null  object
 4   mode_local              18021 non-null  object
 5   measure_length_quarter  18021 non-null  float64
 6   num_distinct_chords     18021 non-null  int64
 7   most_common_chord_root  9880 non-null   float64
 8   most_common_chord_type  9880 non-null   object
 9   degree_relative_to_key  7038 non-null   float64
 10  function                18021 non-null  object
 11  melodic_range           18021 non-null  int64
 12  mean_interval           18021 non-null  float64
 13  large_jump_pct          18021 non-null  float64
 14  num_notes_melody        18021 non-null  int64
 15  avg_duration            18021 non-null  float64
 16  rhythmic_entropy        18021 non-null  float64
 17  most_common_duration    18021 non-null  object
 18  note_density            18021 non-null  int64
 19  pc_0                    18021 non-null  int64
 20  pc_1                    18021 non-null  int64
 21  pc_2                    18021 non-null  int64
 22  pc_3                    18021 non-null  int64
 23  pc_4                    18021 non-null  int64
 24  pc_5                    18021 non-null  int64
 25  pc_6                    18021 non-null  int64
 26  pc_7                    18021 non-null  int64
 27  pc_8                    18021 non-null  int64
 28  pc_9                    18021 non-null  int64
 29  pc_10                   18021 non-null  int64
 30  pc_11                   18021 non-null  int64
 31  has_explicit_harmony    18021 non-null  bool
 32  function_coarse         6467 non-null   object
 33  function_fine           6467 non-null   object
 34  has_melodic_activity    18021 non-null  bool
 35  has_melodic_motion      18021 non-null  bool
dtypes: bool(3), float64(7), int64(17), object(9)
memory usage: 4.6+ MB

In [22]:
check_missing_values(df)

                        Missing Values  Percentage
bwv                                  0    0.000000
movement                             0    0.000000
measure_index                        0    0.000000
key_local                            0    0.000000
mode_local                           0    0.000000
measure_length_quarter               0    0.000000
num_distinct_chords                  0    0.000000
most_common_chord_root            8141   45.175074
most_common_chord_type            8141   45.175074
degree_relative_to_key           10983   60.945564
function                             0    0.000000
melodic_range                        0    0.000000
mean_interval                        0    0.000000
large_jump_pct                       0    0.000000
num_notes_melody                     0    0.000000
avg_duration                         0    0.000000
rhythmic_entropy                     0    0.000000
most_common_duration                 0    0.000000
note_density                         0    0.000000
pc_0                                 0    0.000000
pc_1                                 0    0.000000
pc_2                                 0    0.000000
pc_3                                 0    0.000000
pc_4                                 0    0.000000
pc_5                                 0    0.000000
pc_6                                 0    0.000000
pc_7                                 0    0.000000
pc_8                                 0    0.000000
pc_9                                 0    0.000000
pc_10                                0    0.000000
pc_11                                0    0.000000
has_explicit_harmony                 0    0.000000
function_coarse                  11554   64.114089
function_fine                    11554   64.114089
has_melodic_activity                 0    0.000000
has_melodic_motion                   0    0.000000

# <font color='cyan'>Condicionamento para Completitud de Variables</font>

In [23]:
import pandas as pd

# ------------------------------------------------------------------
# Load conditioned dataset
# ------------------------------------------------------------------

DATA_PATH = (
    r"C:\Users\Aura De La Garza G\Projects\GenAI-Music\unsupervised\curated_data"
    r"\measure_features_conditioned.csv"
)

df = pd.read_csv(DATA_PATH)

print("Dataset shape:", df.shape)

# ------------------------------------------------------------------
# 1. Missing values check
# ------------------------------------------------------------------

print("\n=== Remaining missing values (should be zero) ===\n")
display(
    df.isna()
      .sum()
      .sort_values(ascending=False)
      .to_frame("missing_count")
)

# ------------------------------------------------------------------
# 2. Harmonic conditioning validation
# ------------------------------------------------------------------

print("\n=== Harmonic features when no explicit harmony ===\n")

harmonic_numeric = ["degree_relative_to_key", "num_distinct_chords"]

display(
    df.loc[~df["has_explicit_harmony"], harmonic_numeric]
      .describe()
)

print("\n=== Harmonic categorical placeholders ===\n")

display(
    df[["most_common_chord_root", "most_common_chord_type", "function_coarse"]]
    .value_counts()
    .rename("count")
    .reset_index()
    .head(10)
)

# ------------------------------------------------------------------
# 3. Melodic conditioning validation
# ------------------------------------------------------------------

print("\n=== Melodic motion features when no motion ===\n")

melodic_motion_features = ["melodic_range", "mean_interval", "large_jump_pct"]

display(
    df.loc[~df["has_melodic_motion"], melodic_motion_features]
      .describe()
)

print("\n=== Duration features when no melodic activity ===\n")

duration_features = ["avg_duration", "most_common_duration"]

display(
    df.loc[~df["has_melodic_activity"], duration_features]
      .describe()
)

# ------------------------------------------------------------------
# 4. Rhythmic entropy stability
# ------------------------------------------------------------------

print("\n=== Rhythmic entropy check ===\n")
print("Minimum rhythmic entropy:", df["rhythmic_entropy"].min())

display(
    df["rhythmic_entropy"]
    .describe()
    .to_frame()
)

# ------------------------------------------------------------------
# 5. Binary indicators distribution
# ------------------------------------------------------------------

print("\n=== Helper indicator distributions ===\n")

display(
    df[
        [
            "has_explicit_harmony",
            "has_melodic_activity",
            "has_melodic_motion",
        ]
    ]
    .value_counts()
    .rename("count")
    .reset_index()
)

# ------------------------------------------------------------------
# 6. Pitch-class sparsity sanity check
# ------------------------------------------------------------------

print("\n=== Pitch-class sparsity (mean values) ===\n")

pc_cols = [c for c in df.columns if c.startswith("pc_")]

display(
    df[pc_cols]
    .mean()
    .sort_values(ascending=False)
    .to_frame("mean_value")
)

print("\n✔ All checks complete. Dataset is conditioned and stable.")

Dataset shape: (18021, 36)

=== Remaining missing values (should be zero) ===

                        missing_count
bwv                                 0
movement                            0
measure_index                       0
key_local                           0
mode_local                          0
measure_length_quarter              0
num_distinct_chords                 0
most_common_chord_root              0
most_common_chord_type              0
degree_relative_to_key              0
function                            0
melodic_range                       0
mean_interval                       0
large_jump_pct                      0
num_notes_melody                    0
avg_duration                        0
rhythmic_entropy                    0
most_common_duration                0
note_density                        0
pc_0                                0
pc_1                                0
pc_2                                0
pc_3                                0
pc_4                                0
pc_5                                0
pc_6                                0
pc_7                                0
pc_8                                0
pc_9                                0
pc_10                               0
pc_11                               0
has_explicit_harmony                0
function_coarse                     0
function_fine                       0
has_melodic_activity                0
has_melodic_motion                  0

=== Harmonic features when no explicit harmony ===

       degree_relative_to_key  num_distinct_chords
count                  8141.0               8141.0
mean                      0.0                  0.0
std                       0.0                  0.0
min                       0.0                  0.0
25%                       0.0                  0.0
50%                       0.0                  0.0
75%                       0.0                  0.0
max                       0.0                  0.0

=== Harmonic categorical placeholders ===

  most_common_chord_root most_common_chord_type function_coarse  count
0             NO_HARMONY             NO_HARMONY      NO_HARMONY   8141
1                    2.0                  major      NO_HARMONY   1080
2                    3.0                  major               T    938
3                    0.0                  major               T    696
4                    7.0                  major               S    426
5                    4.0                  major      NO_HARMONY    420
6                    4.0                  minor               T    376
7                    2.0                  minor               S    332
8                    7.0                  minor               T    312
9                    5.0                  major               D    254

=== Melodic motion features when no motion ===

       melodic_range  mean_interval  large_jump_pct
count         7651.0         7651.0          7651.0
mean             0.0            0.0             0.0
std              0.0            0.0             0.0
min              0.0            0.0             0.0
25%              0.0            0.0             0.0
50%              0.0            0.0             0.0
75%              0.0            0.0             0.0
max              0.0            0.0             0.0

=== Duration features when no melodic activity ===

       avg_duration
count        7182.0
mean            0.0
std             0.0
min             0.0
25%             0.0
50%             0.0
75%             0.0
max             0.0

=== Rhythmic entropy check ===

Minimum rhythmic entropy: 0.0

       rhythmic_entropy
count      18021.000000
mean           0.239869
std            0.444708
min            0.000000
25%            0.000000
50%            0.000000
75%            0.371232
max            2.370951

=== Helper indicator distributions ===

   has_explicit_harmony  has_melodic_activity  has_melodic_motion  count
0                  True                  True                True   9661
1                 False                 False               False   7036
2                 False                  True                True    709
3                 False                  True               False    396
4                  True                 False               False    146
5                  True                  True               False     73

=== Pitch-class sparsity (mean values) ===

       mean_value
pc_2     0.053882
pc_9     0.051939
pc_7     0.050497
pc_4     0.048277
pc_0     0.046723
pc_11    0.038511
pc_5     0.035459
pc_6     0.021974
pc_10    0.017424
pc_3     0.015593
pc_8     0.014095
pc_1     0.009322

✔ All checks complete. Dataset is conditioned and stable.

In [24]:
check_missing_values(df)

                        Missing Values  Percentage
bwv                                  0         0.0
movement                             0         0.0
measure_index                        0         0.0
key_local                            0         0.0
mode_local                           0         0.0
measure_length_quarter               0         0.0
num_distinct_chords                  0         0.0
most_common_chord_root               0         0.0
most_common_chord_type               0         0.0
degree_relative_to_key               0         0.0
function                             0         0.0
melodic_range                        0         0.0
mean_interval                        0         0.0
large_jump_pct                       0         0.0
num_notes_melody                     0         0.0
avg_duration                         0         0.0
rhythmic_entropy                     0         0.0
most_common_duration                 0         0.0
note_density                         0         0.0
pc_0                                 0         0.0
pc_1                                 0         0.0
pc_2                                 0         0.0
pc_3                                 0         0.0
pc_4                                 0         0.0
pc_5                                 0         0.0
pc_6                                 0         0.0
pc_7                                 0         0.0
pc_8                                 0         0.0
pc_9                                 0         0.0
pc_10                                0         0.0
pc_11                                0         0.0
has_explicit_harmony                 0         0.0
function_coarse                      0         0.0
function_fine                        0         0.0
has_melodic_activity                 0         0.0
has_melodic_motion                   0         0.0

In [25]:
df['most_common_chord_root'].value_counts()

most_common_chord_root
NO_HARMONY    8141
2.0           1856
7.0           1393
4.0           1326
0.0           1213
3.0           1020
9.0            841
5.0            708
11.0           460
6.0            430
10.0           356
1.0            192
8.0             85
Name: count, dtype: int64

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18021 entries, 0 to 18020
Data columns (total 36 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   bwv                     18021 non-null  object
 1   movement                18021 non-null  object
 2   measure_index           18021 non-null  int64
 3   key_local               18021 non-null  object
 4   mode_local              18021 non-null  object
 5   measure_length_quarter  18021 non-null  float64
 6   num_distinct_chords     18021 non-null  int64
 7   most_common_chord_root  18021 non-null  object
 8   most_common_chord_type  18021 non-null  object
 9   degree_relative_to_key  18021 non-null  float64
 10  function                18021 non-null  object
 11  melodic_range           18021 non-null  int64
 12  mean_interval           18021 non-null  float64
 13  large_jump_pct          18021 non-null  float64
 14  num_notes_melody        18021 non-null  int64
 15  avg_duration            18021 non-null  float64
 16  rhythmic_entropy        18021 non-null  float64
 17  most_common_duration    18021 non-null  object
 18  note_density            18021 non-null  int64
 19  pc_0                    18021 non-null  int64
 20  pc_1                    18021 non-null  int64
 21  pc_2                    18021 non-null  int64
 22  pc_3                    18021 non-null  int64
 23  pc_4                    18021 non-null  int64
 24  pc_5                    18021 non-null  int64
 25  pc_6                    18021 non-null  int64
 26  pc_7                    18021 non-null  int64
 27  pc_8                    18021 non-null  int64
 28  pc_9                    18021 non-null  int64
 29  pc_10                   18021 non-null  int64
 30  pc_11                   18021 non-null  int64
 31  has_explicit_harmony    18021 non-null  bool
 32  function_coarse         18021 non-null  object
 33  function_fine           18021 non-null  object
 34  has_melodic_activity    18021 non-null  bool
 35  has_melodic_motion      18021 non-null  bool
dtypes: bool(3), float64(6), int64(17), object(10)
memory usage: 4.6+ MB

# <font color='cyan'>EDA</font>

In [28]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

DATA_PATH = r"C:\Users\Aura De La Garza G\Projects\GenAI-Music\unsupervised\curated_data\measure_features_conditioned.csv"
df = pd.read_csv(DATA_PATH)

px.defaults.template = "plotly_white"

## 1. Tipología de medida global

In [29]:
activity_counts = (
    df[["has_explicit_harmony", "has_melodic_activity", "has_melodic_motion"]]
    .value_counts()
    .reset_index(name="count")
)

fig = px.bar(
    activity_counts,
    x="count",
    y=["has_explicit_harmony", "has_melodic_activity", "has_melodic_motion"],
    orientation="h",
    title="Tipología de medida global",
    labels={"value": "Activity Present", "count": "Number of Measures"},
)

fig.show()

## 2. Distribución de Función Armónica

In [30]:
counts = df["function_coarse"].value_counts().rename_axis("function_coarse").reset_index(name="count")
fig = px.bar(
    counts,
    x="function_coarse",
    y="count",
    labels={"function_coarse": "Harmonic Function", "count": "Count"},
    title="Distribución de Función Armónica",
)

fig.show()

## 3. Función Armónica por Movimiento

In [31]:
fig = px.histogram(
    df,
    x="function_coarse",
    color="movement",
    barmode="group",
    title="Función Armónica por Movimiento"
)

fig.show()

## 4. Actividad Melódica vs Movimiento Melódico.

In [32]:
melodic_counts = (
    df[["has_melodic_activity", "has_melodic_motion"]]
    .value_counts()
    .reset_index(name="count")
)

fig = px.bar(
    melodic_counts,
    x="count",
    y=["has_melodic_activity", "has_melodic_motion"],
    orientation="h",
    title="Actividad Melódica vs Movimiento Melódico"
)

fig.show()

## 5. Rango Melódico vs Intervalo Promedio

In [33]:
df_motion = df[df["has_melodic_motion"]]

fig = px.scatter(
    df_motion,
    x="melodic_range",
    y="mean_interval",
    color="movement",
    opacity=0.5,
    title="Rango Melódico vs Intervalo Promedio",
)

fig.show()

## 6. Entropía Rítmica por Compás

In [34]:
fig = px.histogram(
    df,
    x="rhythmic_entropy",
    nbins=40,
    title="Distribución de Entropía Rítmica (Por Compás)"
)

fig.show()

## 7. Entropía Rítmica Por Movimiento

In [35]:
fig = px.box(
    df,
    x="movement",
    y="rhythmic_entropy",
    title="Entropía Rítmica por Movimiento"
)

fig.show()

## 8. Perfil Global de Clases de Tono

In [36]:
pc_cols = [f"pc_{i}" for i in range(12)]
pc_mean = df[pc_cols].mean().reset_index()
pc_mean.columns = ["pitch_class", "mean_value"]

fig = px.bar(
    pc_mean,
    x="pitch_class",
    y="mean_value",
    title="Perfil Global de Clases de Tono"
)

fig.show()

## 9. Escasez de Clases de Tono Locales

In [37]:
sample_df = df.sample(300, random_state=42)

fig = px.imshow(
    sample_df[pc_cols].T,
    aspect="auto",
    color_continuous_scale="Blues",
    title="Uso de la Clase de Tono en las Medidas Muestreadas",
)

fig.show()

In [38]:
def eda_musicological_summary(df):
    summary = {}

    # 1. Measure typology
    activity_cols = [
        "has_explicit_harmony",
        "has_melodic_activity",
        "has_melodic_motion"
    ]

    summary["measure_typology"] = (
        df[activity_cols]
        .value_counts(normalize=True)
        .rename("proportion")
        .reset_index()
    )

    # 2. Harmonic function distribution
    summary["harmonic_function_distribution"] = (
        df["function_coarse"]
        .value_counts(normalize=True)
        .rename("proportion")
        .reset_index()
    )

    # 3. Harmonic function by movement (FIXED)
    function_by_movement = (
        df
        .groupby(["movement", "function_coarse"])
        .size()
        .rename("count")
        .reset_index()
    )

    function_by_movement["proportion"] = (
        function_by_movement["count"]
        / function_by_movement.groupby("movement")["count"].transform("sum")
    )

    summary["harmonic_function_by_movement"] = function_by_movement

    # 4. Melodic gesture statistics
    summary["melodic_gesture_stats"] = (
        df[df["has_melodic_motion"]][
            ["melodic_range", "mean_interval", "large_jump_pct"]
        ]
        .describe(percentiles=[0.25, 0.5, 0.75])
    )

    # 5. Rhythmic entropy
    summary["rhythmic_entropy_stats"] = (
        df["rhythmic_entropy"]
        .describe(percentiles=[0.25, 0.5, 0.75])
    )

    summary["rhythmic_entropy_by_movement"] = (
        df
        .groupby("movement")["rhythmic_entropy"]
        .agg(["mean", "median", "std"])
        .sort_values("mean", ascending=False)
    )

    # 6. Pitch-class profile
    pc_cols = [f"pc_{i}" for i in range(12)]

    summary["global_pitch_class_profile"] = (
        df[pc_cols].mean().sort_values(ascending=False)
    )

    pc_sparsity = (df[pc_cols] > 0).sum(axis=1)
    summary["pc_sparsity_stats"] = pc_sparsity.describe()

    return summary

In [39]:
eda_musicological_summary = eda_musicological_summary(df)
print(eda_musicological_summary)

{'measure_typology':    has_explicit_harmony  has_melodic_activity  has_melodic_motion  proportion
0                  True                  True                True    0.536097
1                 False                 False               False    0.390433
2                 False                  True                True    0.039343
3                 False                  True               False    0.021974
4                  True                 False               False    0.008102
5                  True                  True               False    0.004051, 'harmonic_function_distribution':   function_coarse  proportion
0      NO_HARMONY    0.641141
1               T    0.176683
2               S    0.105155
3               D    0.077021, 'harmonic_function_by_movement':            movement function_coarse  count  proportion
0            Adagio               D     26    0.127451
1            Adagio      NO_HARMONY    128    0.627451
2            Adagio               S     16    0.078431
3            Adagio               T     34    0.166667
4           Allegro               D     32    0.091954
..              ...             ...    ...         ...
98        Siciliano               S     30    0.337079
99   Tempo Di Borea               D     12    0.029630
100  Tempo Di Borea      NO_HARMONY    273    0.674074
101  Tempo Di Borea               S     96    0.237037
102  Tempo Di Borea               T     24    0.059259

[103 rows x 4 columns], 'melodic_gesture_stats':        melodic_range  mean_interval  large_jump_pct
count   10370.000000   10370.000000    10370.000000
mean       11.911765       3.532245        0.248253
std         6.114337       1.953557        0.234666
min         0.000000       0.000000        0.000000
25%         7.000000       2.142857        0.000000
50%        12.000000       3.272727        0.200000
75%        17.000000       4.500000        0.400000
max        31.000000      24.000000        1.000000, 'rhythmic_entropy_stats': count    18021.000000
mean         0.239869
std          0.444708
min          0.000000
25%          0.000000
50%          0.000000
75%          0.371232
max          2.370951
Name: rhythmic_entropy, dtype: float64, 'rhythmic_entropy_by_movement':                         mean    median       std
movement
Loure               0.851639  0.970951  0.760307
Boure Anglaise      0.572628  0.779350  0.531688
Andante             0.555650  0.439497  0.525747
Bourree I_Ii        0.455247  0.000000  0.508973
Menuet I_Ii         0.449226  0.000000  0.522575
Sarabande           0.368246  0.000000  0.550241
Adagio              0.346792  0.000000  0.559175
Siciliano           0.331965 -0.000000  0.498171
Grave               0.328227  0.000000  0.538651
Gigue               0.318305 -0.000000  0.488592
Largo               0.318034  0.000000  0.451312
Courante            0.313700  0.000000  0.485035
Gavotte En Rondeau  0.295859 -0.000000  0.421269
Allemanda           0.280168  0.000000  0.478623
Chaconne            0.278478  0.000000  0.522228
Tempo Di Borea      0.247686 -0.000000  0.412493
Allemande           0.244192 -0.000000  0.414524
Gavotte I_Ii        0.237928  0.000000  0.402072
Minuet I_Ii         0.224775 -0.000000  0.412127
Fugue               0.147168  0.000000  0.355860
Prelude             0.077822  0.000000  0.260339
Allegro Assai       0.062874 -0.000000  0.189776
Presto              0.031640  0.000000  0.158718
Allegro             0.016763  0.000000  0.090103
Double Presto       0.015594 -0.000000  0.098070
Boure               0.014979  0.000000  0.110871
Double              0.014493  0.000000  0.100763
Corrente            0.011665  0.000000  0.090508, 'global_pitch_class_profile': pc_2     0.053882
pc_9     0.051939
pc_7     0.050497
pc_4     0.048277
pc_0     0.046723
pc_11    0.038511
pc_5     0.035459
pc_6     0.021974
pc_10    0.017424
pc_3     0.015593
pc_8     0.014095
pc_1     0.009322
dtype: float64, 'pc_sparsity_stats': count    18021.000000
mean         0.229621
std          1.141922
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          9.000000
dtype: float64}

# <font color='cyan'>PCA y Kmeans</font>

In [40]:
import pandas as pd
import plotly.express as px

pca_df = pd.read_csv(r"C:\Users\Aura De La Garza G\Projects\GenAI-Music\unsupervised\modeled_data\pca_measure_features.csv")

In [41]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Aura De La Garza G\Projects\GenAI-Music\unsupervised\modeled_data\modeled_measure_features.csv")

# Check
df.head()

,bwv,movement,measure_index,key_local,mode_local,measure_length_quarter,num_distinct_chords,most_common_chord_root,most_common_chord_type,degree_relative_to_key,...,pc_8,pc_9,pc_10,pc_11,has_explicit_harmony,function_coarse,function_fine,has_melodic_activity,has_melodic_motion,cluster
0,BWV1013,Allemande,1,C,major,4.0,1,9.0,minor,6.0,...,0,0,0,0,True,T,T,True,True,3
1,BWV1013,Allemande,2,C,major,4.0,1,2.0,minor,2.0,...,0,0,0,0,True,S,S,True,True,0
2,BWV1013,Allemande,3,C,major,4.0,1,2.0,minor,2.0,...,0,0,0,0,True,S,S,True,True,0
3,BWV1013,Allemande,4,C,major,4.0,1,2.0,minor,2.0,...,0,0,0,0,True,S,S,True,True,0
4,BWV1013,Allemande,5,C,major,4.0,1,11.0,unknown,7.0,...,0,0,0,0,True,D,D,True,True,3

In [42]:
# 2D PCA scatter
fig = px.scatter(
    pca_df, x='PCA_1', y='PCA_2', color='cluster', 
    title="Clusters Visualizados en 2 componentes principales",
    hover_data=pca_df.columns
)
fig.show()

# 3D PCA scatter (if >=3 components)
fig = px.scatter_3d(
    pca_df, x='PCA_1', y='PCA_2', z='PCA_3', color='cluster',
    title="Clusters Visualizados en 3 componentes principales",
    hover_data=pca_df.columns
)
fig.show()

# <font color='cyan'>Perfilamiento</font>

In [46]:
# Load the modeled dataset that already has clusters
df = pd.read_csv(
    r"C:\Users\Aura De La Garza G\Projects\GenAI-Music\unsupervised\modeled_data\modeled_measure_features.csv"
)
print(df.columns)  # confirm 'cluster' is there

Index(['bwv', 'movement', 'measure_index', 'key_local', 'mode_local',
       'measure_length_quarter', 'num_distinct_chords',
       'most_common_chord_root', 'most_common_chord_type',
       'degree_relative_to_key', 'function', 'melodic_range', 'mean_interval',
       'large_jump_pct', 'num_notes_melody', 'avg_duration',
       'rhythmic_entropy', 'most_common_duration', 'note_density', 'pc_0',
       'pc_1', 'pc_2', 'pc_3', 'pc_4', 'pc_5', 'pc_6', 'pc_7', 'pc_8', 'pc_9',
       'pc_10', 'pc_11', 'has_explicit_harmony', 'function_coarse',
       'function_fine', 'has_melodic_activity', 'has_melodic_motion',
       'cluster'],
      dtype='object')

In [47]:
numeric_features = [
    'melodic_range','mean_interval','large_jump_pct','avg_duration',
    'note_density','rhythmic_entropy','degree_relative_to_key','num_distinct_chords',
] + [f'pc_{i}' for i in range(12)]

# Group by cluster on original (unscaled) data
cluster_profile = df.groupby('cluster')[numeric_features].agg(['mean','median','std'])

# Flatten MultiIndex for easier reading
cluster_profile.columns = ['_'.join(col).strip() for col in cluster_profile.columns.values]

# Display full table
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)
display(cluster_profile)

,melodic_range_mean,melodic_range_median,melodic_range_std,mean_interval_mean,mean_interval_median,mean_interval_std,large_jump_pct_mean,large_jump_pct_median,large_jump_pct_std,avg_duration_mean,avg_duration_median,avg_duration_std,note_density_mean,note_density_median,note_density_std,rhythmic_entropy_mean,rhythmic_entropy_median,rhythmic_entropy_std,degree_relative_to_key_mean,degree_relative_to_key_median,degree_relative_to_key_std,num_distinct_chords_mean,num_distinct_chords_median,num_distinct_chords_std,pc_0_mean,pc_0_median,pc_0_std,pc_1_mean,pc_1_median,pc_1_std,pc_2_mean,pc_2_median,pc_2_std,pc_3_mean,pc_3_median,pc_3_std,pc_4_mean,pc_4_median,pc_4_std,pc_5_mean,pc_5_median,pc_5_std,pc_6_mean,pc_6_median,pc_6_std,pc_7_mean,pc_7_median,pc_7_std,pc_8_mean,pc_8_median,pc_8_std,pc_9_mean,pc_9_median,pc_9_std,pc_10_mean,pc_10_median,pc_10_std,pc_11_mean,pc_11_median,pc_11_std
cluster,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,12.539160,12.0,6.194766,3.580178,3.357143,1.961169,0.269352,0.230769,0.249999,0.524634,0.500000,0.487783,10.186463,8.0,4.851061,0.040767,-0.000000,0.137767,0.142894,0.0,1.154955,1.336100,1.0,0.871276,0.123444,0.0,0.526161,0.021266,0.0,0.198735,0.130705,0.0,0.544308,0.038122,0.0,0.293198,0.143154,0.0,0.566002,0.087656,0.0,0.441191,0.060425,0.0,0.383486,0.133558,0.0,0.593571,0.030861,0.0,0.237435,0.157417,0.0,0.626573,0.032936,0.0,0.265049,0.114367,0.0,0.528945
1,9.621236,9.0,5.833463,3.196177,2.750000,2.072918,0.201838,0.166667,0.225802,0.632003,0.571429,0.317639,6.990174,7.0,3.024666,1.070372,0.970951,0.316407,1.491284,1.0,2.377534,1.423772,1.0,0.816836,0.030428,0.0,0.228778,0.010143,0.0,0.128000,0.047861,0.0,0.293543,0.021553,0.0,0.173127,0.021236,0.0,0.188086,0.035816,0.0,0.256156,0.020602,0.0,0.181291,0.048494,0.0,0.291270,0.025990,0.0,0.215055,0.027575,0.0,0.236628,0.028843,0.0,0.204867,0.017750,0.0,0.154212
2,0.075343,0.0,0.520963,0.039154,0.000000,0.252220,0.000000,0.000000,0.000000,0.054431,0.000000,0.210050,0.164944,0.0,0.770414,0.000169,0.000000,0.008539,0.012557,0.0,0.234625,0.023806,0.0,0.158348,0.000916,0.0,0.030248,0.001831,0.0,0.042757,0.002878,0.0,0.082428,0.002485,0.0,0.054797,0.001570,0.0,0.039590,0.000785,0.0,0.032341,0.001177,0.0,0.034293,0.001962,0.0,0.059400,0.001177,0.0,0.047144,0.001831,0.0,0.045714,0.000654,0.0,0.030254,0.002747,0.0,0.052342
3,13.147994,13.0,6.012875,3.697162,3.500000,1.922018,0.267153,0.250000,0.218027,0.383384,0.333333,0.179587,10.650223,10.0,4.334255,0.233927,-0.000000,0.347360,5.099257,5.0,1.104370,1.633284,1.0,1.054895,0.078158,0.0,0.441744,0.011887,0.0,0.141678,0.087370,0.0,0.424542,0.013967,0.0,0.150646,0.071025,0.0,0.393929,0.054086,0.0,0.334392,0.026449,0.0,0.211617,0.067459,0.0,0.366430,0.013076,0.0,0.135127,0.067756,0.0,0.345065,0.027043,0.0,0.245373,0.052303,0.0,0.319219

# <font color='cyan'>Número Óptimo de Clusters</font>

## Prueba de la Silueta y del Codo

In [44]:
import plotly.graph_objects as go
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import numpy as np
import pandas as pd
from pathlib import Path

# ------------------------------------------------------------------
# Load dataset
# ------------------------------------------------------------------
IN_PATH = Path(
    r"C:\Users\Aura De La Garza G\Projects\GenAI-Music\unsupervised\curated_data"
    r"\measure_features_conditioned.csv"
)
df = pd.read_csv(IN_PATH)

# ------------------------------------------------------------------
# Numeric features for clustering
# ------------------------------------------------------------------
numeric_features = [
    'melodic_range','mean_interval','large_jump_pct','avg_duration',
    'note_density','rhythmic_entropy','degree_relative_to_key','num_distinct_chords',
] + [f'pc_{i}' for i in range(12)]
X = df[numeric_features]

# ------------------------------------------------------------------
# Scaling
# ------------------------------------------------------------------
z_scores = np.abs((X - X.mean()) / X.std())
outlier_fraction = (z_scores > 3).any(axis=1).mean()
scaler = RobustScaler() if outlier_fraction > 0.05 else StandardScaler()
X_scaled = scaler.fit_transform(X)

# ------------------------------------------------------------------
# PCA (retain 90% variance)
# ------------------------------------------------------------------
pca = PCA(n_components=0.9, random_state=42)
X_pca = pca.fit_transform(X_scaled)

# ------------------------------------------------------------------
# Determine optimal number of clusters
# ------------------------------------------------------------------
k_range = range(2, 15)  # adjust the range if needed
inertia = []
silhouette = []

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    labels = kmeans.fit_predict(X_pca)
    inertia.append(kmeans.inertia_)
    silhouette.append(silhouette_score(X_pca, labels))

# ------------------------------------------------------------------
# Interactive Elbow Plot
# ------------------------------------------------------------------
fig_elbow = go.Figure()
fig_elbow.add_trace(go.Scatter(
    x=list(k_range),
    y=inertia,
    mode='lines+markers',
    name='Inertia',
    marker=dict(color='blue', size=10)
))
fig_elbow.update_layout(
    title='Elbow Method for Optimal k',
    xaxis_title='Number of Clusters (k)',
    yaxis_title='Inertia',
    template='plotly_white'
)
fig_elbow.show()

# ------------------------------------------------------------------
# Interactive Silhouette Plot
# ------------------------------------------------------------------
fig_sil = go.Figure()
fig_sil.add_trace(go.Scatter(
    x=list(k_range),
    y=silhouette,
    mode='lines+markers',
    name='Silhouette Score',
    marker=dict(color='green', size=10)
))
fig_sil.update_layout(
    title='Silhouette Score for Different k',
    xaxis_title='Number of Clusters (k)',
    yaxis_title='Silhouette Score',
    template='plotly_white'
)
fig_sil.show()